<?php

/*
 * Template Name: FAQ(EN)
 */

get_header();
?>
<section id="faq_sec1" class="flex_part">
	<div class="part1 part inviewfadeInUp">
    <h2>
      <img src="<?php echo get_template_directory_uri()?>/assets/images/logo_en.png" alt="">
    </h2>
    <h3>
      <img src="<?php echo get_template_directory_uri()?>/assets/images/faq_ttl.png" alt="">
    </h3>
	</div>
  <div class="part2 inviewfadeInUp">
    <dl>
      <dt class="inviewfadeInUp">
        <span class="mark">Q.</span>
        <span>When will this game be released?</span>
      </dt>
      <dd class="inviewfadeInUp">
        <span class="mark">A.</span>
        <span>The game will be released in August 2022 after prerelease testing from May to June 2022.</span>
      </dd>
    </dl>
    <dl>
      <dt class="inviewfadeInUp">
        <span class="mark">Q.</span>
        <span>How do you plan to connect the blockchain?</span>
      </dt>
      <dd class="inviewfadeInUp">
        <span class="mark">A.</span>
        <span>
          MV token adopts Polygon and MATIC blockchain.<br>
          We uses Polygon and MATIC for NFT, Metamask wallet, and OpenSea, the NFT market.<br>
          Regarding cryptocurrency exchanges, MV token will be listed in UniSwap, Quickswap, Sushiswap, TrustPad, ChainBoost, etc. sequentially.
        </span>
      </dd>
    </dl>
    <dl>
      <dt class="inviewfadeInUp">
        <span class="mark">Q.</span>
        <span>What is UGC to Earn?</span>
      </dt>
      <dd class="inviewfadeInUp">
        <span class="mark">A.</span>
        <span>
          UGC is an acronym for "User Generated Contents" and refers to contents generated by users..
          As the word "UGC to Earn" implies, those who have staked more than a certain amount of MV tokens will be granted the right to incorporate UGC into their games.<br>
          This will allow them to create their own "fashionable costumes" in the game and sell them as NFT products.<br>
          They can build their own brands in the game and obtain cryptocurrencies on the marketplace.
          Other than that, they can get the ownership of certain "maps" and "dungeons" by staking MV tokens.<br>
          This is the right to arrange the design of the objects in the area, design the monsters that appear, and set the "rare items" owned by the owner as rare drop items for the monsters that appear.<br>
          They can set an entrance fee for this map and get entrance fees from other players.<br>
          *These rights sales of UGC to Earn will be available with the update after the service is released.
        </span>
      </dd>
    </dl>
    <dl>
      <dt class="inviewfadeInUp">
        <span class="mark">Q.</span>
        <span>What is a fashionable costume?</span>
      </dt>
      <dd class="inviewfadeInUp">
        <span class="mark">A.</span>
        <span>
          In this game, there is equipment called "stylish costumes" in addition to the concept of "weapons" and "armor" in general RPGs.<br>
          By equipping stylish costumes, you can change your character's appearance, enhance your fighting ability in battle, and use special skills to broaden your strategy.<br>
          The official costumes will be made available through NFT auctions, and will also be sold as MV tokens.<br>
          The costumes can be imported into the game as NFTs or exported out of the game, and can be traded in the NFT marketplace.
        </span>
      </dd>
    </dl>
    <dl>
      <dt class="inviewfadeInUp">
        <span class="mark">Q.</span>
        <span>About the function of fashionable equipment NFT</span>
      </dt>
      <dd class="inviewfadeInUp">
        <span class="mark">A.</span>
        <span>
        Fashionable equipments have various functions, and you can have a variety of effects by combining them using MVs.<br>
        <br>
        Functions of fashionable equipments<br>
        ・Change character appearance<br>
        └ Character appearance can be changed.<br>
        └ All 7 parts (head, body, legs, shoulders, back, right hand, left hand)<br>
        ・Effects<br>
        └ Some rare items have special effects (such as an aura of fire coming from the entire body).<br>
        ・Status increases<br>
        └ Effects that increase the character's strength.<br>
        └ HP, MP, arm strength, physical strength, intelligence, spirit, dexterity, speed, etc.
        ・Vintage effects<br>
        └ The more time that passes since the old fashionable item was manufactured, the more the 
        Vintage effect is an effect that increases status.<br>
        ・Special skills and motions<br>
        └ You can use buffs (parameter enhancements) and attack skills with powerful effects.<br>
        └ You can set up a special motion as the motion when you use a skill.<br>
        ・Fashionable equipments enhancement<br>
        └ If you use the surplus fashion items as materials, you can improve the ability of the fashion items themselves.<br>
        ・You can combine the main fashionable equipment with the sub-fashionable equipment.<br>
        └  Adding various fashions to the sub-slots of your main fashions will allow you to combine the status-raising effects and skills of those fashions.<br>
        └ Sub-fashioning has no effect on appearance.<br>
        └ You can add up to 10 sub-fashionable items to a single part of the body.<br>
        ・Appearance fashion<br>
        └ The main fashionable equipments tends to be chosen for its performance.<br>
         In addition, you can also set up a separate "appearance-only" slot where you can change the favorite appearance of your fashionable equipment.<br>
        ・Fashionable memory function for each job<br>
        └ When you change jobs, it will be difficult to change the fashionable equipment. Fashion equipment can be set separately for each occupation.<br>
        ・Fashion set registration function<br>
        └ You can register up to 10 sets of fashionable equipments for each character.<br>
        └ You can switch between registered fashionable equipments at any time.<br>
        ・Stylish rental function<br>
        └ You can rent out your fashions to other players. (For details, refer to "Scholarship System")<br>
        ・Burn fashionable equipments to improve other fashionable equipments.<br>
        └ By combining fashionable equipment, you can enhance the fashionable equipments combined.<br>
        ・Function that allows NPC (Non-Player Character) characters in the Metaverse space to dress up in their own fashionable equipments<br>
        </span>
      </dd>
    </dl>
    <dl>
      <dt class="inviewfadeInUp">
        <span class="mark">Q.</span>
        <span>About the scholarship system of fashionable equipment NFT</span>
      </dt>
      <dd class="inviewfadeInUp">
        <span class="mark">A.</span>
        <span>
        You can rent your fashionable equipment to other players.<br>
        Rentals is possible for any number of people as long as you have the fashionable equipment.<br>
        When renting, the renter must pay a certain amount of MV to start the rental process.<br>
        <br>
        Fashionable equipment is expensive and limited in number, so it may not be available for purchase.<br>
        Players who cannot afford to buy the equipment can borrow it from other players and play with it.<br>
        The player who borrows the fashionable equipment must pay the renter a predetermined percentage of the reward earned during the rental period.<br>
        The owner can earn a lot of money by renting out the fashionable equipment to multiple users without having to play it himself.<br>
        The player who borrows the equipment can play with a stronger character for a fee paid to the owner. By playing with a stronger character,
        It will be easier to earn income in the game.<br>
        Each character can be equipped with 7 different parts of fashionable equipment.<br>
        A character who rents all 7 parts of the fashionable equipment must distribute the income of 7 parts to owners of 7 fashionable equipments.<br>
        <br>
        The rented fashionable equipment can be collected whenever the owner wants to collect it.
        The borrower, on the other hand, cannot return the equipment during the minimum rental period.
        </span>
      </dd>
    </dl>
  </div>
</section>
<?php
get_footer();
